<a href="https://colab.research.google.com/github/kalaiavk1516-create/python_numby_pandas_project/blob/main/Copy_of_Untitled6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
temperatures_w1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
print("shape:",temperatures_w1.shape)
print("data type:", temperatures_w1.dtype)
print("number of elements:", temperatures_w1.size)

shape: (7,)
data type: float64
number of elements: 7


In [ ]:
temperatures_f = (temperatures_w1 * 9/5) + 32
print("temperatures in fahrenheit:")
print(temperatures_f)

temperatures in fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [ ]:
print("maximum temperatures:", temperatures_w1.max())
print("minimum temperatures:", temperatures_w1.min())
print("mean temperatures:", temperatures_w1.mean())

maximum temperatures: 26.1
minimum temperatures: 20.8
mean temperatures: 23.542857142857144


In [ ]:
print("firt 3 days:", temperatures_w1[:3])

firt 3 days: [22.5 25.3 20.8]


In [ ]:
print("weekend:", temperatures_w1[-2:1])

weekend: []


In [ ]:
print("middle 3 days:", temperatures_w1[2:5])

middle 3 days: [20.8 23.4 26.1]


In [ ]:
import numpy as np

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2,22.5,21.3,24.0,23.5,22.8,20.1]
])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [ ]:
print("shape:", temperatures.shape)
print("data type:", temperatures.dtype)
print("number of elements:", temperatures.size)

shape: (2, 7)
data type: float64
number of elements: 14


In [ ]:
print("week 1:", temperatures[0])

week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
print("week 1:", temperatures[1])

week 1: [19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [ ]:
print("week 1 weekend:", temperatures[0, -2:])

week 1 weekend: [24.8 21.9]


In [ ]:
print("week 1 weekend:", temperatures[1, -2:])

week 1 weekend: [22.8 20.1]


In [ ]:
import pandas as pd

marks = pd.Series([95,92,89,85,80], index=["Rank1","Rank2","Rank3","Rank4","Rank5"])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [ ]:
print(marks[0])

95


/tmp/ipykernel_1232/3296141910.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[0])


In [ ]:
print(marks.loc[["Rank1","Rank2","Rank3"]])

Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [ ]:
print(marks.iloc[2])

89


In [ ]:
print(marks[marks > 90])

Rank1    95
Rank2    92
dtype: int64


In [ ]:
marks.loc["rank1"] = 100
print(marks)

Rank1     95
Rank2     92
Rank3     89
Rank4     85
Rank5     80
rank1    100
dtype: int64


In [ ]:
marks = marks.drop("Rank5")
print(marks)

Rank1     95
Rank2     92
Rank3     89
Rank4     85
rank1    100
dtype: int64


In [ ]:
cgpa = marks / 10
print(cgpa)

Rank1     9.5
Rank2     9.2
Rank3     8.9
Rank4     8.5
rank1    10.0
dtype: float64


In [ ]:
import pandas as pd

transactions = pd.DataFrame({
    "transactionID": [101,102,103,104,105,106,107,108,109,110],
    "product category": ["Electronics","Clothing","Electronics","Furniture","Clothing",
                         "Electronics","Furniture","Clothing","Furniture","Electronics"],
    "Region": ["North","South","North","East","West",
               "North","East","West","South","North"],
    "Amount": [200,150,300,450,200,250,300,180,350,400]
})
print(transactions)

   transactionID product category Region  Amount
0            101      Electronics  North     200
1            102         Clothing  South     150
2            103      Electronics  North     300
3            104        Furniture   East     450
4            105         Clothing   West     200
5            106      Electronics  North     250
6            107        Furniture   East     300
7            108         Clothing   West     180
8            109        Furniture  South     350
9            110      Electronics  North     400


In [ ]:
print(transactions.head())

   transactionID product category Region  Amount
0            101      Electronics  North     200
1            102         Clothing  South     150
2            103      Electronics  North     300
3            104        Furniture   East     450
4            105         Clothing   West     200


In [ ]:
print(transactions.tail())

   transactionID product category Region  Amount
5            106      Electronics  North     250
6            107        Furniture   East     300
7            108         Clothing   West     180
8            109        Furniture  South     350
9            110      Electronics  North     400


In [ ]:
print(transactions.shape)

(10, 4)


In [ ]:
print(transactions.columns)

Index(['transactionID', 'product category', 'Region', 'Amount'], dtype='object')


In [ ]:
print(transactions.dtypes)

transactionID        int64
product category    object
Region              object
Amount               int64
dtype: object


In [ ]:
print(transactions.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   transactionID     10 non-null     int64 
 1   product category  10 non-null     object
 2   Region            10 non-null     object
 3   Amount            10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes
None


In [ ]:
print(transactions [["product category", "Amount"]])

  product category  Amount
0      Electronics     200
1         Clothing     150
2      Electronics     300
3        Furniture     450
4         Clothing     200
5      Electronics     250
6        Furniture     300
7         Clothing     180
8        Furniture     350
9      Electronics     400


In [ ]:
print(transactions.iloc[:,-3:])

  product category Region  Amount
0      Electronics  North     200
1         Clothing  South     150
2      Electronics  North     300
3        Furniture   East     450
4         Clothing   West     200
5      Electronics  North     250
6        Furniture   East     300
7         Clothing   West     180
8        Furniture  South     350
9      Electronics  North     400


In [ ]:
filtered_data = transactions[(transactions["Region"] == "North") & (transactions["Amount"] > 200)]
print(filtered_data)

   transactionID product category Region  Amount
2            103      Electronics  North     300
5            106      Electronics  North     250
9            110      Electronics  North     400


In [ ]:
print(transactions["product category"].value_counts())

product category
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [ ]:
print(transactions["Region"].unique())

['North' 'South' 'East' 'West']


In [ ]:
print(transactions.groupby("Region")["Amount"].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [ ]:
transactions.loc[transactions["transactionID"] == 102, "Amount"] = 165

print(transactions)

   transactionID product category Region  Amount
0            101      Electronics  North     200
1            102         Clothing  South     165
2            103      Electronics  North     300
3            104        Furniture   East     450
4            105         Clothing   West     200
5            106      Electronics  North     250
6            107        Furniture   East     300
7            108         Clothing   West     180
8            109        Furniture  South     350
9            110      Electronics  North     400


In [ ]:
transactions["Discount"] = transactions["Amount"] * 0.10
print(transactions)

   transactionID product category Region  Amount  Discount
0            101      Electronics  North     200      20.0
1            102         Clothing  South     165      16.5
2            103      Electronics  North     300      30.0
3            104        Furniture   East     450      45.0
4            105         Clothing   West     200      20.0
5            106      Electronics  North     250      25.0
6            107        Furniture   East     300      30.0
7            108         Clothing   West     180      18.0
8            109        Furniture  South     350      35.0
9            110      Electronics  North     400      40.0


In [ ]:
transactions = transactions[
transactions["transactionID"] != 109]
print(transactions)

   transactionID product category Region  Amount  Discount
0            101      Electronics  North     200      20.0
1            102         Clothing  South     165      16.5
2            103      Electronics  North     300      30.0
3            104        Furniture   East     450      45.0
4            105         Clothing   West     200      20.0
5            106      Electronics  North     250      25.0
6            107        Furniture   East     300      30.0
7            108         Clothing   West     180      18.0
9            110      Electronics  North     400      40.0


In [ ]:
transactions = transactions.drop(columns=["Discount"])
print(transactions)

   transactionID product category Region  Amount
0            101      Electronics  North     200
1            102         Clothing  South     165
2            103      Electronics  North     300
3            104        Furniture   East     450
4            105         Clothing   West     200
5            106      Electronics  North     250
6            107        Furniture   East     300
7            108         Clothing   West     180
9            110      Electronics  North     400
